# Writes the generated MSL passes into a C header (one source string per pass).
import os, sys
work, out, names = sys.argv[1], sys.argv[2], sys.argv[3:]
what = os.environ.get('FSR_HEADER_WHAT', 'upscaler passes')
lines = ['// Generated by tools/fsr3/ -- do not edit.',
         f'// AMD FidelityFX Super Resolution 3.1.4 {what}, translated GLSL -> SPIR-V -> MSL.',
         '// Copyright (C) 2024 Advanced Micro Devices, Inc. Released under the MIT licence:',
         '// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated',
         '// documentation files (the "Software"), to deal in the Software without restriction, including without limitation the',
         '// rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit',
         '// persons to whom the Software is furnished to do so, subject to the following conditions: The above copyright notice and',
         '// this permission notice shall be included in all copies or substantial portions of the Software.',
         '// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED.',
         '#pragma once', '']
for n in names:
    src = open(f'{work}/{n}.metal').read()
    lines.append(f'static const char kFsrSource_{n}[] =')
    for l in src.split('\n'):
        lines.append('    "' + l.replace('\\', '\\\\').replace('"', '\\"') + '\\n"')
    lines.append(';')
    lines.append('')
open(out, 'w').write('\n'.join(lines))
